# permissions for end users to view fbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fb-viewer-role
rules:
- apiGroups:
  - foo.my.domain
  resources:
  - fbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - foo.my.domain
  resources:
  - fbs/status
  verbs:
  - get
